# pubspec.yaml
name: train_os
description: A professional fitness tracking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^4.0.2
  shared_preferences: ^2.2.2
  fl_chart: ^1.0.0 
  permission_handler: ^11.3.1
  intl: ^0.19.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/train_os_icon.png
cupertino_icons: ^1.0.8
flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/train_os_icon.png"

